site_name: Order Hub - Documentation
site_url: https://adam-patalong-aurora.github.io/order-hub-api-doc/

docs_dir: docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pl
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - Home Page: index.md
  - Authorization:
      - authorization/index.md
  - Orders:
      - orders/index.md
      - orders/create.md
      - orders/update.md

plugins:
  - search:
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          name: English
          build: true
          site_name: "Order Hub - Api Documentation"
        - locale: pl
          default: true
          name: Polish
          build: true
          site_name: "Order Hub - Dokumentacja API"
          theme:
            palette:
              primary: red
          nav_translations:
            Home Page: Strona Główna
            Authorization: Autoryzacja
            Orders: Zamówienia

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

copyright: Copyright © 2024 Aurora Creation Sp. z o.o. (https://auroracreation.com)


